### PR TITLE
Upgrade to XMLSpy rel3 sp1

### PR DESCRIPTION
**Pull request by gjtimmerman**
Upgraded the package to XMLSpy rel3 sp1

### CODE REVIEW

**Comment by riezebosch** [comment]
I guess https://github.com/riezebosch/BoxstarterPackages/pull/36/commits/40e45729e4673231b9539fa1d3390768852e4594 is a mistake?

**Comment by gjtimmerman** [comment]
Why a mistake? I added the chocolatey package.

**Comment by riezebosch** [comment]
You don't have to since it's published from a CI/CD pipeline 🤓

**Comment by gjtimmerman** [comment]
Sorry, didn't know that. You can ignore it.

**Comment by gjtimmerman** [comment]
Thanks. It works.

**Pull request closed without merging**
