### PR TITLE
Improvements to MSSQLServer2014Express, IIS Package

### PR DESCRIPTION
**Pull request by The-Running-Dev**
MSSQLServer2014Express
Added support for local and remote configuration file,
Added support for overriding of any parameter from the command line.

IIS package

### CODE REVIEW

**Comment by riezebosch** [comment]
Why all the hassle about custom command line parameters when that is already supported by chocolatey? You can pass additional paramaters using the `-ia` switch and you can override package defined parameters by adding the `-o` switch. Wouldn't that suffice? See also this other https://github.com/riezebosch/BoxstarterPackages/pull/8 related the 2016 version of SQL Express.

**Comment by The-Running-Dev** [comment]
You know...I don't remember anymore. I've been working and refining this for a couple of months. Let me test passing the parameters with the -ia switch, and I'll get back to you.

**Comment by The-Running-Dev** [comment]
I'm going to delete this, and re-create it when I test it.

**Comment by riezebosch** [comment]
Thanks

Op di 6 dec. 2016 19:28 schreef Boyan Kostadinov <notifications@github.com>:

**Pull request closed without merging**
