### PR TITLE
Updated Docker Toolbox to v18.09.0

### PR DESCRIPTION
**Pull request by igorgatis**
https://github.com/docker/docker-ce/releases/tag/v18.09.0

### CODE REVIEW

**Comment by riezebosch** [comment]
It is supposed to auto-update: https://github.com/riezebosch/BoxstarterPackages/blob/master/docker-toolbox/Update.ps1

Would rather fix that.

**Comment by igorgatis** [comment]
Am I supposed to run it? Or should one of the project maintenaners do it?

**Comment by riezebosch** [comment]
If you want to contribute you can try to fix the AU update because it probably broken. Otherwise you wouldn't have to do this PR in the first place. Trying to fix is installing `AU` with `choco install au -y` and then run `update` in the package root folder.

Maybe I'll find some time tonight to look for it myself.

Update: it should be solved by this https://github.com/riezebosch/BoxstarterPackages/commit/0db82ab71f0fe982eb1467632d20af82b81fde9f but the download url has changed https://github.com/riezebosch/BoxstarterPackages/commit/59a2cbf210e4a9c64ea32496d4b9c18d912298b2

The `-ce` seems to be dropped and your url is not working anymore. Is that correct?

**Comment by riezebosch** [comment]
I think it's done with the fix on auto update?

**Comment by igorgatis** [comment]
I think this is all good. Thanks!

**Comment by igorgatis** [comment]
For some reason, it always downloads the install package over and over:

```
docker-toolbox v18.09.0 [Approved]
docker-toolbox package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was 'C9D9D8EF38D3713DEEBDAE83606CF71E485A3D4824D2468562C74747E1971962'.
Downloading docker-toolbox
  from 'https://github.com/docker/toolbox/releases/download/v18.09.0/DockerToolbox-18.09.0.exe'
```

Everytime I issue `choco install -y docker-toolbox`, the line
`Error - hashes do not match. Actual value was ...` appears with a different value.

**Comment by riezebosch** [comment]
Then probably a new version is published on the same download url. Will look into it tomorrow. In the meantime you can pass in ` --ignore-checksum` to continue installing.

**Update**: I've run it over and over again but getting the same checksums and even the chocolatey test service approves. So I guess the checksum is right and you have some weird issue on your side?

**Pull request closed without merging**
